"""
Centralized configuration for the RAG pipeline.
"""

import os

# --- Paths ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STORES_DIR = os.path.join(BASE_DIR, "stores")
DOWNLOADS_DIR = os.path.expanduser(os.environ.get("DOCCHAT_DOWNLOADS_DIR", "~/Downloads"))

# --- Supported file types ---
SUPPORTED_EXTENSIONS = {".pdf", ".txt", ".docx", ".csv"}

# --- Chunking ---
CHUNK_SIZE = 900
CHUNK_OVERLAP = 150

# --- Embedding ---
EMBED_MODEL = "sentence-transformers/all-mpnet-base-v2"

# --- Reranking ---
RERANK_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

# --- Retrieval ---
RETRIEVAL_FETCH_K = 20       # chunks per query from vector store
BM25_FETCH_K = 20            # chunks per query from BM25
NUM_QUERY_VARIATIONS = 3     # extra queries generated by LLM
RERANK_TOP_K = 6             # final chunks after reranking
RRF_K = 60                   # reciprocal rank fusion constant

# --- LLM ---
GROQ_MODEL = "llama-3.3-70b-versatile"
LLM_TEMPERATURE = 0.2

# --- Conversation ---
MAX_HISTORY_TURNS = 5

# --- Agent ---
MAX_AGENT_ITERATIONS = 8
AGENT_MAX_DOCS_PER_CALL = 6      # how many chunks each tool call returns
AGENT_MAX_CHARS_PER_DOC = 900    # chars kept per chunk in tool output
AGENT_MAX_TOTAL_CHARS = 6000     # hard cap on a single tool's output
